/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bookmark {
  'id' : bigint,
  'userId' : Principal,
  'questionId' : bigint,
}
export type ContentType = { 'notes' : null } |
  { 'formula' : null };
export interface DailyQuestion {
  'id' : bigint,
  'date' : bigint,
  'questionId' : bigint,
}
export type ExamType = { 'jee' : null } |
  { 'neet' : null };
export interface LeaderboardEntry {
  'id' : bigint,
  'userName' : string,
  'userId' : Principal,
  'totalScore' : bigint,
  'examType' : ExamType,
  'testsCompleted' : bigint,
}
export interface Question {
  'id' : bigint,
  'subject' : Subject,
  'difficulty' : bigint,
  'correctAnswer' : bigint,
  'year' : bigint,
  'questionText' : string,
  'solution' : string,
  'chapter' : string,
  'examType' : ExamType,
  'options' : Array<string>,
}
export interface QuestionCreation {
  'subject' : Subject,
  'difficulty' : bigint,
  'correctAnswer' : bigint,
  'year' : bigint,
  'questionText' : string,
  'solution' : string,
  'chapter' : string,
  'examType' : ExamType,
  'options' : Array<string>,
}
export interface StudyMaterial {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'subject' : Subject,
  'contentType' : ContentType,
  'chapter' : string,
}
export type Subject = { 'maths' : null } |
  { 'biology' : null } |
  { 'chemistry' : null } |
  { 'physics' : null };
export interface Test {
  'id' : bigint,
  'title' : string,
  'subject' : [] | [Subject],
  'testType' : TestType,
  'durationMinutes' : bigint,
  'questionIds' : Array<bigint>,
  'chapter' : [] | [string],
  'examType' : ExamType,
}
export type TestType = { 'full' : null } |
  { 'chapter' : null };
export interface UserProfile { 'id' : bigint, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookmark' : ActorMethod<[bigint], bigint>,
  'addQuestion' : ActorMethod<[QuestionCreation], bigint>,
  'addStudyMaterial' : ActorMethod<[StudyMaterial], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTest' : ActorMethod<[Test], bigint>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getAllStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getAllTests' : ActorMethod<[], Array<Test>>,
  'getBookmarks' : ActorMethod<[], Array<Bookmark>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExamPersistentId' : ActorMethod<[], bigint>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getQuestion' : ActorMethod<[bigint], Question>,
  'getStudyMaterial' : ActorMethod<[bigint], StudyMaterial>,
  'getTest' : ActorMethod<[bigint], Test>,
  'getTodayDailyQuestion' : ActorMethod<[], [] | [DailyQuestion]>,
  'getUserPersistentId' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeBookmark' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchQuestionsBySubjectAndChapter' : ActorMethod<
    [Subject, string],
    Array<Question>
  >,
  'seedData' : ActorMethod<[], undefined>,
  'setDailyQuestion' : ActorMethod<[bigint], bigint>,
  'submitTest' : ActorMethod<[bigint, Array<bigint>], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];