/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Variant({
  'maths' : IDL.Null,
  'biology' : IDL.Null,
  'chemistry' : IDL.Null,
  'physics' : IDL.Null,
});
export const ExamType = IDL.Variant({ 'jee' : IDL.Null, 'neet' : IDL.Null });
export const QuestionCreation = IDL.Record({
  'subject' : Subject,
  'difficulty' : IDL.Nat,
  'correctAnswer' : IDL.Nat,
  'year' : IDL.Nat,
  'questionText' : IDL.Text,
  'solution' : IDL.Text,
  'chapter' : IDL.Text,
  'examType' : ExamType,
  'options' : IDL.Vec(IDL.Text),
});
export const ContentType = IDL.Variant({
  'notes' : IDL.Null,
  'formula' : IDL.Null,
});
export const StudyMaterial = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : Subject,
  'contentType' : ContentType,
  'chapter' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TestType = IDL.Variant({
  'full' : IDL.Null,
  'chapter' : IDL.Null,
});
export const Test = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Opt(Subject),
  'testType' : TestType,
  'durationMinutes' : IDL.Nat,
  'questionIds' : IDL.Vec(IDL.Nat),
  'chapter' : IDL.Opt(IDL.Text),
  'examType' : ExamType,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'subject' : Subject,
  'difficulty' : IDL.Nat,
  'correctAnswer' : IDL.Nat,
  'year' : IDL.Nat,
  'questionText' : IDL.Text,
  'solution' : IDL.Text,
  'chapter' : IDL.Text,
  'examType' : ExamType,
  'options' : IDL.Vec(IDL.Text),
});
export const Bookmark = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'questionId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const LeaderboardEntry = IDL.Record({
  'id' : IDL.Nat,
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
  'totalScore' : IDL.Nat,
  'examType' : ExamType,
  'testsCompleted' : IDL.Nat,
});
export const DailyQuestion = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'questionId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'addQuestion' : IDL.Func([QuestionCreation], [IDL.Nat], []),
  'addStudyMaterial' : IDL.Func([StudyMaterial], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTest' : IDL.Func([Test], [IDL.Nat], []),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getAllTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExamPersistentId' : IDL.Func([], [IDL.Nat], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
  'getStudyMaterial' : IDL.Func([IDL.Nat], [StudyMaterial], ['query']),
  'getTest' : IDL.Func([IDL.Nat], [Test], ['query']),
  'getTodayDailyQuestion' : IDL.Func([], [IDL.Opt(DailyQuestion)], ['query']),
  'getUserPersistentId' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBookmark' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchQuestionsBySubjectAndChapter' : IDL.Func(
      [Subject, IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'seedData' : IDL.Func([], [], []),
  'setDailyQuestion' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'submitTest' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Variant({
    'maths' : IDL.Null,
    'biology' : IDL.Null,
    'chemistry' : IDL.Null,
    'physics' : IDL.Null,
  });
  const ExamType = IDL.Variant({ 'jee' : IDL.Null, 'neet' : IDL.Null });
  const QuestionCreation = IDL.Record({
    'subject' : Subject,
    'difficulty' : IDL.Nat,
    'correctAnswer' : IDL.Nat,
    'year' : IDL.Nat,
    'questionText' : IDL.Text,
    'solution' : IDL.Text,
    'chapter' : IDL.Text,
    'examType' : ExamType,
    'options' : IDL.Vec(IDL.Text),
  });
  const ContentType = IDL.Variant({ 'notes' : IDL.Null, 'formula' : IDL.Null });
  const StudyMaterial = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : Subject,
    'contentType' : ContentType,
    'chapter' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TestType = IDL.Variant({ 'full' : IDL.Null, 'chapter' : IDL.Null });
  const Test = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Opt(Subject),
    'testType' : TestType,
    'durationMinutes' : IDL.Nat,
    'questionIds' : IDL.Vec(IDL.Nat),
    'chapter' : IDL.Opt(IDL.Text),
    'examType' : ExamType,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'subject' : Subject,
    'difficulty' : IDL.Nat,
    'correctAnswer' : IDL.Nat,
    'year' : IDL.Nat,
    'questionText' : IDL.Text,
    'solution' : IDL.Text,
    'chapter' : IDL.Text,
    'examType' : ExamType,
    'options' : IDL.Vec(IDL.Text),
  });
  const Bookmark = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'questionId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const LeaderboardEntry = IDL.Record({
    'id' : IDL.Nat,
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
    'totalScore' : IDL.Nat,
    'examType' : ExamType,
    'testsCompleted' : IDL.Nat,
  });
  const DailyQuestion = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'questionId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'addQuestion' : IDL.Func([QuestionCreation], [IDL.Nat], []),
    'addStudyMaterial' : IDL.Func([StudyMaterial], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTest' : IDL.Func([Test], [IDL.Nat], []),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getAllTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExamPersistentId' : IDL.Func([], [IDL.Nat], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
    'getStudyMaterial' : IDL.Func([IDL.Nat], [StudyMaterial], ['query']),
    'getTest' : IDL.Func([IDL.Nat], [Test], ['query']),
    'getTodayDailyQuestion' : IDL.Func([], [IDL.Opt(DailyQuestion)], ['query']),
    'getUserPersistentId' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBookmark' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchQuestionsBySubjectAndChapter' : IDL.Func(
        [Subject, IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'seedData' : IDL.Func([], [], []),
    'setDailyQuestion' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'submitTest' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };