/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    id: bigint;
    userName: string;
    userId: Principal;
    totalScore: bigint;
    examType: ExamType;
    testsCompleted: bigint;
}
export interface QuestionCreation {
    subject: Subject;
    difficulty: bigint;
    correctAnswer: bigint;
    year: bigint;
    questionText: string;
    solution: string;
    chapter: string;
    examType: ExamType;
    options: Array<string>;
}
export interface Bookmark {
    id: bigint;
    userId: Principal;
    questionId: bigint;
}
export interface StudyMaterial {
    id: bigint;
    title: string;
    content: string;
    subject: Subject;
    contentType: ContentType;
    chapter: string;
}
export interface Test {
    id: bigint;
    title: string;
    subject?: Subject;
    testType: TestType;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
    chapter?: string;
    examType: ExamType;
}
export interface Question {
    id: bigint;
    subject: Subject;
    difficulty: bigint;
    correctAnswer: bigint;
    year: bigint;
    questionText: string;
    solution: string;
    chapter: string;
    examType: ExamType;
    options: Array<string>;
}
export interface DailyQuestion {
    id: bigint;
    date: bigint;
    questionId: bigint;
}
export interface UserProfile {
    id: bigint;
    name: string;
}
export enum ContentType {
    notes = "notes",
    formula = "formula"
}
export enum ExamType {
    jee = "jee",
    neet = "neet"
}
export enum Subject {
    maths = "maths",
    biology = "biology",
    chemistry = "chemistry",
    physics = "physics"
}
export enum TestType {
    full = "full",
    chapter = "chapter"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBookmark(questionId: bigint): Promise<bigint>;
    addQuestion(question: QuestionCreation): Promise<bigint>;
    addStudyMaterial(material: StudyMaterial): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTest(test: Test): Promise<bigint>;
    getAllQuestions(): Promise<Array<Question>>;
    getAllStudyMaterials(): Promise<Array<StudyMaterial>>;
    getAllTests(): Promise<Array<Test>>;
    getBookmarks(): Promise<Array<Bookmark>>;
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getExamPersistentId(): Promise<bigint>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getQuestion(id: bigint): Promise<Question>;
    getStudyMaterial(id: bigint): Promise<StudyMaterial>;
    getTest(id: bigint): Promise<Test>;
    getTodayDailyQuestion(): Promise<DailyQuestion | null>;
    getUserPersistentId(): Promise<bigint>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeBookmark(bookmarkId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchQuestionsBySubjectAndChapter(subject: Subject, chapter: string): Promise<Array<Question>>;
    seedData(): Promise<void>;
    setDailyQuestion(questionId: bigint): Promise<bigint>;
    submitTest(testId: bigint, answers: Array<bigint>): Promise<bigint>;
}
import type { ContentType as _ContentType, DailyQuestion as _DailyQuestion, ExamType as _ExamType, LeaderboardEntry as _LeaderboardEntry, Question as _Question, QuestionCreation as _QuestionCreation, StudyMaterial as _StudyMaterial, Subject as _Subject, Test as _Test, TestType as _TestType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBookmark(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookmark(arg0);
            return result;
        }
    }
    async addQuestion(arg0: QuestionCreation): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(to_candid_QuestionCreation_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(to_candid_QuestionCreation_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStudyMaterial(arg0: StudyMaterial): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudyMaterial(to_candid_StudyMaterial_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudyMaterial(to_candid_StudyMaterial_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTest(arg0: Test): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTest(to_candid_Test_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTest(to_candid_Test_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudyMaterials(): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudyMaterials();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudyMaterials();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTests(): Promise<Array<Test>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTests();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTests();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookmarks(): Promise<Array<Bookmark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookmarks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookmarks();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExamPersistentId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamPersistentId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamPersistentId();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestion(arg0: bigint): Promise<Question> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestion(arg0);
                return from_candid_Question_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestion(arg0);
            return from_candid_Question_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudyMaterial(arg0: bigint): Promise<StudyMaterial> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyMaterial(arg0);
                return from_candid_StudyMaterial_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyMaterial(arg0);
            return from_candid_StudyMaterial_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTest(arg0: bigint): Promise<Test> {
        if (this.processError) {
            try {
                const result = await this.actor.getTest(arg0);
                return from_candid_Test_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTest(arg0);
            return from_candid_Test_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayDailyQuestion(): Promise<DailyQuestion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayDailyQuestion();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayDailyQuestion();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPersistentId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPersistentId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPersistentId();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeBookmark(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBookmark(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchQuestionsBySubjectAndChapter(arg0: Subject, arg1: string): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchQuestionsBySubjectAndChapter(to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchQuestionsBySubjectAndChapter(to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async setDailyQuestion(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.setDailyQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDailyQuestion(arg0);
            return result;
        }
    }
    async submitTest(arg0: bigint, arg1: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTest(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ContentType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ExamType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExamType): ExamType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntry_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_StudyMaterial_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyMaterial): StudyMaterial {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TestType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestType): TestType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Test_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Test): Test {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subject]): Subject | null {
    return value.length === 0 ? null : from_candid_Subject_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyQuestion]): DailyQuestion | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    subject: _Subject;
    difficulty: bigint;
    correctAnswer: bigint;
    year: bigint;
    questionText: string;
    solution: string;
    chapter: string;
    examType: _ExamType;
    options: Array<string>;
}): {
    id: bigint;
    subject: Subject;
    difficulty: bigint;
    correctAnswer: bigint;
    year: bigint;
    questionText: string;
    solution: string;
    chapter: string;
    examType: ExamType;
    options: Array<string>;
} {
    return {
        id: value.id,
        subject: from_candid_Subject_n20(_uploadFile, _downloadFile, value.subject),
        difficulty: value.difficulty,
        correctAnswer: value.correctAnswer,
        year: value.year,
        questionText: value.questionText,
        solution: value.solution,
        chapter: value.chapter,
        examType: from_candid_ExamType_n22(_uploadFile, _downloadFile, value.examType),
        options: value.options
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    subject: _Subject;
    contentType: _ContentType;
    chapter: string;
}): {
    id: bigint;
    title: string;
    content: string;
    subject: Subject;
    contentType: ContentType;
    chapter: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        subject: from_candid_Subject_n20(_uploadFile, _downloadFile, value.subject),
        contentType: from_candid_ContentType_n27(_uploadFile, _downloadFile, value.contentType),
        chapter: value.chapter
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    subject: [] | [_Subject];
    testType: _TestType;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
    chapter: [] | [string];
    examType: _ExamType;
}): {
    id: bigint;
    title: string;
    subject?: Subject;
    testType: TestType;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
    chapter?: string;
    examType: ExamType;
} {
    return {
        id: value.id,
        title: value.title,
        subject: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.subject)),
        testType: from_candid_TestType_n33(_uploadFile, _downloadFile, value.testType),
        durationMinutes: value.durationMinutes,
        questionIds: value.questionIds,
        chapter: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.chapter)),
        examType: from_candid_ExamType_n22(_uploadFile, _downloadFile, value.examType)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userName: string;
    userId: Principal;
    totalScore: bigint;
    examType: _ExamType;
    testsCompleted: bigint;
}): {
    id: bigint;
    userName: string;
    userId: Principal;
    totalScore: bigint;
    examType: ExamType;
    testsCompleted: bigint;
} {
    return {
        id: value.id,
        userName: value.userName,
        userId: value.userId,
        totalScore: value.totalScore,
        examType: from_candid_ExamType_n22(_uploadFile, _downloadFile, value.examType),
        testsCompleted: value.testsCompleted
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maths: null;
} | {
    biology: null;
} | {
    chemistry: null;
} | {
    physics: null;
}): Subject {
    return "maths" in value ? Subject.maths : "biology" in value ? Subject.biology : "chemistry" in value ? Subject.chemistry : "physics" in value ? Subject.physics : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jee: null;
} | {
    neet: null;
}): ExamType {
    return "jee" in value ? ExamType.jee : "neet" in value ? ExamType.neet : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notes: null;
} | {
    formula: null;
}): ContentType {
    return "notes" in value ? ContentType.notes : "formula" in value ? ContentType.formula : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    full: null;
} | {
    chapter: null;
}): TestType {
    return "full" in value ? TestType.full : "chapter" in value ? TestType.chapter : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudyMaterial>): Array<StudyMaterial> {
    return value.map((x)=>from_candid_StudyMaterial_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Test>): Array<Test> {
    return value.map((x)=>from_candid_Test_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n39(_uploadFile, _downloadFile, x));
}
function to_candid_ContentType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ExamType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamType): _ExamType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionCreation_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionCreation): _QuestionCreation {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_StudyMaterial_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyMaterial): _StudyMaterial {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TestType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestType): _TestType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Test_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Test): _Test {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    subject?: Subject;
    testType: TestType;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
    chapter?: string;
    examType: ExamType;
}): {
    id: bigint;
    title: string;
    subject: [] | [_Subject];
    testType: _TestType;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
    chapter: [] | [string];
    examType: _ExamType;
} {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject ? candid_some(to_candid_Subject_n3(_uploadFile, _downloadFile, value.subject)) : candid_none(),
        testType: to_candid_TestType_n15(_uploadFile, _downloadFile, value.testType),
        durationMinutes: value.durationMinutes,
        questionIds: value.questionIds,
        chapter: value.chapter ? candid_some(value.chapter) : candid_none(),
        examType: to_candid_ExamType_n5(_uploadFile, _downloadFile, value.examType)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: Subject;
    difficulty: bigint;
    correctAnswer: bigint;
    year: bigint;
    questionText: string;
    solution: string;
    chapter: string;
    examType: ExamType;
    options: Array<string>;
}): {
    subject: _Subject;
    difficulty: bigint;
    correctAnswer: bigint;
    year: bigint;
    questionText: string;
    solution: string;
    chapter: string;
    examType: _ExamType;
    options: Array<string>;
} {
    return {
        subject: to_candid_Subject_n3(_uploadFile, _downloadFile, value.subject),
        difficulty: value.difficulty,
        correctAnswer: value.correctAnswer,
        year: value.year,
        questionText: value.questionText,
        solution: value.solution,
        chapter: value.chapter,
        examType: to_candid_ExamType_n5(_uploadFile, _downloadFile, value.examType),
        options: value.options
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    subject: Subject;
    contentType: ContentType;
    chapter: string;
}): {
    id: bigint;
    title: string;
    content: string;
    subject: _Subject;
    contentType: _ContentType;
    chapter: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        subject: to_candid_Subject_n3(_uploadFile, _downloadFile, value.subject),
        contentType: to_candid_ContentType_n9(_uploadFile, _downloadFile, value.contentType),
        chapter: value.chapter
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    notes: null;
} | {
    formula: null;
} {
    return value == ContentType.notes ? {
        notes: null
    } : value == ContentType.formula ? {
        formula: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestType): {
    full: null;
} | {
    chapter: null;
} {
    return value == TestType.full ? {
        full: null
    } : value == TestType.chapter ? {
        chapter: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    maths: null;
} | {
    biology: null;
} | {
    chemistry: null;
} | {
    physics: null;
} {
    return value == Subject.maths ? {
        maths: null
    } : value == Subject.biology ? {
        biology: null
    } : value == Subject.chemistry ? {
        chemistry: null
    } : value == Subject.physics ? {
        physics: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamType): {
    jee: null;
} | {
    neet: null;
} {
    return value == ExamType.jee ? {
        jee: null
    } : value == ExamType.neet ? {
        neet: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
